-- AlterTable
ALTER TABLE `user` ALTER COLUMN `id` DROP DEFAULT,
    ALTER COLUMN `childId` DROP DEFAULT,
    ALTER COLUMN `email` DROP DEFAULT,
    ALTER COLUMN `img` DROP DEFAULT,
    ALTER COLUMN `name` DROP DEFAULT;
